# version: 1.0.0
#forestglow
command_timeout = 1000
add_newline = false

format = """
[â–‘â–’â–“](fg:#a5d6a7)\
[ ğŸŒ² ](bg:#a5d6a7 fg:#1b5e20)\
[î‚´](bg:#66bb6a fg:#a5d6a7)\
$directory\
[î‚´](fg:#66bb6a bg:#8d6e63)\
$git_branch$git_status\
[î‚´](fg:#8d6e63 bg:#6d4c41)\
$rust$python$nodejs\
[î‚´](fg:#6d4c41 bg:#2e2e2e)\
$time\
[î‚´ ](fg:#2e2e2e)\
$line_break$character
"""

[line_break]
disabled = true

[character]
success_symbol = "[ğŸŒ¿](bold green)"
error_symbol = "[ğŸ§¨](bold red)"

[username]
style_user = "fg:#4caf50"
show_always = true

[directory]
style = "fg:#ffffff bg:#66bb6a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "ğŸªº "
"Music" = "ğŸµ "
"Pictures" = "ğŸ–¼ "

[git_branch]
symbol = "ğŸªµ "
style = "bg:#8d6e63"
format = '[[ $symbol $branch ](fg:#ffffff bg:#8d6e63)]($style)'

[git_status]
style = "bg:#8d6e63"
format = '[[ ($all_status$ahead_behind) ](fg:#ffffff bg:#8d6e63)]($style)'
conflicted = 'âš ï¸'
ahead = 'â¡ï¸ ${count}'
behind = 'â¬…ï¸ ${count}'
diverged = ' â†”ï¸ â¡ï¸${ahead_count} â¬…ï¸${behind_count}'
up_to_date = ' ğŸ“… '
untracked = 'ğŸ—ƒï¸ '
stashed = 'ğŸ“¦ '
modified = 'ğŸª‘ '
staged = '[ ğŸ“¤\($count\)](bg:color_lime)'
renamed = 'ğŸ“¥'
deleted = 'ğŸ—‘ï¸ '

[rust]
symbol = "ğŸª“"
style = "bg:#6d4c41"
format = '[[ $symbol ($version) ](fg:#a1887f bg:#6d4c41)]($style)'

[python]
symbol = "ğŸ"
style = "bg:#6d4c41"
format = '[[ $symbol ($version) ](fg:#a1887f bg:#6d4c41)]($style)'
python_binary = "python"

[nodejs]
symbol = "ğŸŒ°"
style = "bg:#6d4c41"
format = '[[ $symbol ($version) ](fg:#a1887f bg:#6d4c41)]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#2e2e2e"
format = '[[ â³ $time ](fg:#cfd8dc bg:#2e2e2e)]($style)'