#zoomies
command_timeout = 1000

add_newline = false

format = """
[î‚¶](fg:#a16a5e)\
$os\
$username\
[î‚°](bg:#87af87 fg:#a16a5e)\
$directory\
[î‚°](fg:#87af87 bg:#af87af)\
$git_branch$git_status\
[î‚°](fg:#af87af bg:#af875f)\
$python\
[î‚°](fg:#af875f bg:#af5f5f)\
$nodejs\
[î‚°](fg:#af5f5f bg:#afaf5f)\
$rust\
[î‚°](fg:#afaf5f bg:#665c54)\
$docker_context\
[î‚°](fg:#665c54 bg:#3c3836)\
$time\
[î‚´ ](fg:#3c3836)\
$line_break$character
"""

[palettes.zooprompt]
color_fg0 = "#fbf1c7"
color_bg1 = "#3c3836"
color_bg3 = "#665c54"
color_tortoise = "#87af87"
color_elephant = "#af87af"
color_snake = "#af875f"
color_lion = "#af5f5f"
color_squirrel = "#afaf5f"
color_fox = "#a16a5e"


[os]
disabled = false
style = "bg:#a16a5e fg:#fbf1c7"

[os.symbols]
Macos = "ó°€µ"
Linux = "ó°Œ½"
Ubuntu = "ó°•ˆ"
Windows = "ó°²"


[username]
show_always = true
style_user = "bg:#a16a5e fg:#fbf1c7"
style_root = "bg:#a16a5e fg:#fbf1c7"
format = '[ $user ]($style)'

[directory]
style = "fg:#fbf1c7 bg:#87af87"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "ğŸ¢ "

[directory.substitutions]
"Documents" = "ğŸ“„"
"Downloads" = "ğŸ“¥"
"Music" = "ğŸµ"
"Pictures" = "ğŸ“¸"
"Developer" = "ğŸ’»"


[git_branch]
symbol = "ğŸ˜"
style = "bg:#af87af"
format = '[[  $symbol $branch ](fg:#fbf1c7 bg:#af87af)]($style)'

[git_status]
style = "bg:#af87af"
format = '[[($all_status$ahead_behind )](fg:#fbf1c7 bg:#af87af)]($style)'
conflicted = 'ó±§´'
ahead = 'ó±¦´ ${count}'
behind = 'ó±¦¶ ${count}'
diverged = ' ó±¦¸ ó±¦´${ahead_count} ó±¦¶${behind_count}'
up_to_date = ' ó±¦º '
untracked = ''
stashed = 'îƒ'
modified = 'ğŸ¦´ '
staged = '[ ó±«‰\($count\)](bg:color_lime)'
renamed = 'ó±§¬'
deleted = 'ó±«Š '

[python]
symbol = "ğŸ"
style = "bg:#af875f"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#af875f)]($style)'
python_binary = "python"

[nodejs]
symbol = "ğŸ¦"
style = "bg:#af5f5f"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#af5f5f)]($style)'

[rust]
symbol = "ğŸ¦«"
style = "bg:#afaf5f"
format = '[[ $symbol ($version) ](fg:#fbf1c7 bg:#afaf5f)]($style)'

[docker_context]
symbol = "ğŸ³"
style = "bg:#665c54"
format = '[[ $symbol ($context) ](fg:#fbf1c7 bg:#665c54)]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#3c3836"
format = '[[ â° $time ](fg:#fbf1c7 bg:#3c3836)]($style)'

[line_break]
disabled = true

[character]
success_symbol = "[ğŸ¾](bold green)"
error_symbol = "[ğŸ’¢](bold red)"

